import React, { createContext, useContext, useState, useEffect } from 'react'
import { Language } from '@/lib/supabase'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string>) => string
  isRTL: boolean
}

const translations = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.amount': 'Amount',
    'common.date': 'Date',
    'common.status': 'Status',
    'common.description': 'Description',
    'common.balance': 'Balance',
    'common.currency': 'SYP',

    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.phoneNumber': 'Phone Number',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signUp': 'Sign Up',
    'auth.signIn': 'Sign In',
    'auth.role': 'I am a',
    'auth.passenger': 'Passenger',
    'auth.driver': 'Driver',
    'auth.merchant': 'Merchant',
    'auth.eventAdmin': 'Event Organizer',
    'auth.accountType': 'Account Type',
    'auth.getStartedDescription': 'Get started with your digital wallet in minutes',
    'auth.fullNamePlaceholder': 'Your full name',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.phoneNumberPlaceholder': 'XXX XXX XXX',
    'auth.createPasswordPlaceholder': 'Create a strong password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.signInHere': 'Sign in here',
    'auth.signUpHere': 'Sign up for free',
    'auth.accessDescription': 'Access your digital wallet and manage your payments',
    'auth.enterPasswordPlaceholder': 'Enter your password',
    'auth.rememberMe': 'Remember me',

    'common.optional': 'Optional',

    // Role Features
    'features.digitalWallet': 'Digital wallet access',
    'features.qrPayments': 'QR code payments',
    'features.eventTickets': 'Event ticket purchases',
    'features.transactionHistory': 'Transaction history',
    'features.driverDashboard': 'Driver dashboard',
    'features.earningsTracking': 'Earnings tracking',
    'features.qrGeneration': 'QR code generation',
    'features.tripManagement': 'Trip management',
    'features.businessDashboard': 'Business dashboard',
    'features.paymentProcessing': 'Payment processing',
    'features.analyticsInsights': 'Analytics & insights',
    'features.customerManagement': 'Customer management',
    'features.eventCreation': 'Event creation',
    'features.ticketManagement': 'Ticket management',
    'features.attendeeAnalytics': 'Attendee analytics',
    'features.revenueTracking': 'Revenue tracking',

    // Registration Features Headers
    'registration.personalAccountFeatures': 'Personal Account Features',
    'registration.driverAccountFeatures': 'Driver Account Features',
    'registration.businessAccountFeatures': 'Business Account Features',
    'registration.eventOrganizerFeatures': 'Event Organizer Features',
    'registration.whyChooseTickets': 'Why Choose Tickets?',
    'registration.bankGradeSecurity': 'Bank-grade security & encryption',
    'registration.instantTransactions': 'Instant transactions & real-time updates',
    'registration.customerSupport': '24/7 customer support',
    'registration.lowFees': 'Low fees & transparent pricing',
    'registration.soc2Certified': 'SOC 2 Certified',
    'registration.iso27001': 'ISO 27001',
    'registration.pciCompliant': 'PCI Compliant',
    'registration.joinRevolution': 'Join the digital payment revolution',
    'registration.backToHome': 'Back to Home',

    // Login Page
    'login.welcomeBack': 'Welcome back',
    'login.secure': 'Secure',
    'login.encrypted': 'Encrypted',
    'login.private': 'Private',

    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.wallet': 'Wallet',
    'nav.transactions': 'Transactions',
    'nav.scanner': 'QR Scanner',
    'nav.events': 'Events',
    'nav.tickets': 'My Tickets',
    'nav.earnings': 'Earnings',
    'nav.trips': 'Trips',
    'nav.verification': 'Verification',
    'nav.qrcode': 'QR Code',
    'nav.business': 'Business',
    'nav.management': 'Management',
    'nav.analytics': 'Analytics',
    'nav.users': 'Users',
    'nav.disputes': 'Disputes',
    'nav.verificationReview': 'Driver Verification',
    'nav.support': 'Support',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',

    // Wallet
    'wallet.title': 'Digital Wallet',
    'wallet.balance': 'Current Balance',
    'wallet.recharge': 'Recharge Wallet',
    'wallet.rechargeAmount': 'Recharge Amount',
    'wallet.paymentMethod': 'Payment Method',
    'wallet.mtnCash': 'MTN Cash',
    'wallet.syriatelCash': 'Syriatel Cash',
    'wallet.shamCash': 'ShamCash',
    'wallet.fatora': 'Fatora',
    'wallet.stripe': 'Credit Card',
    'wallet.rechargeSuccess': 'Wallet recharged successfully',
    'wallet.insufficientBalance': 'Insufficient balance',

    // Transactions
    'transactions.title': 'Transaction History',
    'transactions.recent': 'Recent Transactions',
    'transactions.payment': 'Payment',
    'transactions.recharge': 'Recharge',
    'transactions.refund': 'Refund',
    'transactions.withdrawal': 'Withdrawal',
    'transactions.pending': 'Pending',
    'transactions.completed': 'Completed',
    'transactions.failed': 'Failed',
    'transactions.cancelled': 'Cancelled',
    'transactions.to': 'To',
    'transactions.from': 'From',

    // QR Scanner
    'scanner.title': 'QR Code Scanner',
    'scanner.scanToPayDriver': 'Scan driver QR to pay for transport',
    'scanner.scanToPayMerchant': 'Scan merchant QR to make payment',
    'scanner.scanning': 'Scanning...',
    'scanner.paymentSuccess': 'Payment successful',
    'scanner.paymentFailed': 'Payment failed',
    'scanner.quantity': 'Number of tickets',

    // Events
    'events.title': 'Events',
    'events.upcoming': 'Upcoming Events',
    'events.myEvents': 'My Events',
    'events.createEvent': 'Create Event',
    'events.eventTitle': 'Event Title',
    'events.eventDescription': 'Event Description',
    'events.eventLocation': 'Location',
    'events.eventDate': 'Date',
    'events.eventPrice': 'Ticket Price',
    'events.availableTickets': 'Available Tickets',
    'events.buyTicket': 'Buy Ticket',
    'events.ticketPurchased': 'Ticket purchased successfully',

    // Driver
    'driver.title': 'Driver Dashboard',
    'driver.earnings': 'Earnings',
    'driver.todayEarnings': "Today's Earnings",
    'driver.weekEarnings': 'Week Earnings',
    'driver.monthEarnings': 'Month Earnings',
    'driver.generateQR': 'Generate QR Code',
    'driver.activeTrip': 'Active Trip',
    'driver.startTrip': 'Start Trip',
    'driver.endTrip': 'End Trip',
    'driver.route': 'Route',
    'driver.ticketFee': 'Ticket Fee',
    'driver.passengerCount': 'Passengers',
    'driver.analytics': 'Driver Analytics',
    'driver.performance': 'Performance',
    'driver.efficiency': 'Efficiency',
    'driver.monthlyComparison': 'Monthly Comparison',
    'driver.hourlyPerformance': 'Hourly Performance',
    'driver.locationPerformance': 'Location Performance',
    'driver.ratingDistribution': 'Rating Distribution',
    'driver.performanceMetrics': 'Performance Metrics',
    'driver.earningsBreakdown': 'Earnings Breakdown',
    'driver.todaySnapshot': "Today's Snapshot",
    'driver.exportAnalytics': 'Export Analytics',
    'driver.earningsTrend': 'Earnings Trend',
    'driver.dailyAverage': 'Daily Average',
    'driver.weeklyAverage': 'Weekly Average',
    'driver.monthlyAverage': 'Monthly Average',
    'driver.totalNetEarnings': 'Total Net Earnings',
    'driver.averagePerTrip': 'Average per Trip',
    'driver.totalDistance': 'Total Distance',
    'driver.totalDuration': 'Total Duration',
    'driver.earningsPerHour': 'Earnings per Hour',
    'driver.earningsPerKm': 'Earnings per KM',
    'driver.cancellationRate': 'Cancellation Rate',
    'driver.overallRating': 'Overall Rating',
    'driver.efficiencyRating': 'Efficiency Rating',
    'driver.excellent': 'Excellent',

    // Driver Verification
    'driver.verification.title': 'Driver Verification',
    'driver.verification.description': 'Complete your driver verification to start earning with Tickets',
    'driver.verification.status.title': 'Verification Status',
    'driver.verification.status.not_submitted': 'Not Submitted',
    'driver.verification.status.pending': 'Under Review',
    'driver.verification.status.approved': 'Approved',
    'driver.verification.status.rejected': 'Rejected',
    'driver.verification.progress': 'Progress',
    'driver.verification.driverInfo': 'Driver Information',
    'driver.verification.driverInfoDesc': 'Provide your driver and vehicle details',
    'driver.verification.licenseNumber': 'License Number',
    'driver.verification.licenseNumberPlaceholder': 'Enter your driving license number',
    'driver.verification.licenseExpiry': 'License Expiry Date',
    'driver.verification.vehicleType': 'Vehicle Type',
    'driver.verification.selectVehicleType': 'Select vehicle type',
    'driver.verification.vehicleModel': 'Vehicle Model',
    'driver.verification.vehicleModelPlaceholder': 'e.g., Toyota Hiace 2020',
    'driver.verification.vehiclePlate': 'Vehicle Plate Number',
    'driver.verification.vehiclePlatePlaceholder': 'e.g., 123456 Damascus',
    'driver.verification.routeName': 'Route Name',
    'driver.verification.routeNamePlaceholder': 'e.g., Damascus-Aleppo',
    'driver.verification.routeDescription': 'Route Description',
    'driver.verification.routeDescriptionPlaceholder': 'Describe your regular routes and stops',
    'driver.verification.documents': 'Required Documents',
    'driver.verification.documentsDesc': 'Upload clear photos or scans of your documents',
    'driver.verification.documentTypes.license_front': 'Driver License (Front)',
    'driver.verification.documentTypes.license_back': 'Driver License (Back)',
    'driver.verification.documentTypes.vehicle_registration': 'Vehicle Registration',
    'driver.verification.documentTypes.vehicle_photo': 'Vehicle Photo',
    'driver.verification.viewDocument': 'View Document',
    'driver.verification.submit': 'Submit for Review',
    'driver.verification.invalidFileType': 'Please upload images (JPG, PNG) or PDF files only',
    'driver.verification.fileTooLarge': 'File size must be less than 5MB',
    'driver.verification.documentUploaded': 'Document uploaded successfully',
    'driver.verification.uploadFailed': 'Failed to upload document. Please try again.',
    'driver.verification.fillRequired': 'Please fill in all required fields',
    'driver.verification.uploadAllDocuments': 'Please upload all required documents',
    'driver.verification.submitted': 'Verification submitted successfully! You will be notified when reviewed.',
    'driver.verification.rejectedMessage': 'Your verification was rejected. Please review the feedback and resubmit.',
    'driver.verification.approvedMessage': 'Congratulations! Your driver verification has been approved. You can now start accepting passengers.',
    'driver.verification.vehicleTypes.bus': 'Bus',
    'driver.verification.vehicleTypes.microbus': 'Microbus',
    'driver.verification.vehicleTypes.taxi': 'Taxi',
    'driver.verification.vehicleTypes.private_car': 'Private Car',
    'driver.verification.vehicleTypes.motorcycle': 'Motorcycle',
    'driver.verification.vehicleTypes.truck': 'Truck',
    'common.saving': 'Saving...',

    // Merchant
    'merchant.title': 'Merchant Dashboard',
    'merchant.business': 'Business Information',
    'merchant.businessName': 'Business Name',
    'merchant.businessCategory': 'Category',
    'merchant.generateQR': 'Generate Payment QR',
    'merchant.qrAmount': 'Payment Amount',

    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.userManagement': 'User Management',
    'admin.systemAnalytics': 'System Analytics',
    'admin.totalUsers': 'Total Users',
    'admin.totalTransactions': 'Total Transactions',
    'admin.totalRevenue': 'Total Revenue',
    'admin.disputes': 'Disputes',

    // App Name
    'app.name': 'Tickets',
    'app.subtitle': 'Digital Wallet & Payment System',
    'app.welcome': 'Welcome to Tickets',
    'app.description': 'Your digital wallet for seamless payments, event tickets, and transportation in Syria.',

    // Onboarding
    'onboard.welcome': 'Welcome to Tickets!',
    'onboard.step1.title': 'Digital Wallet',
    'onboard.step1.desc': 'Securely store and manage your money digitally',
    'onboard.step2.title': 'QR Payments',
    'onboard.step2.desc': 'Pay for transportation and purchases instantly',
    'onboard.step3.title': 'Event Tickets',
    'onboard.step3.desc': 'Buy and manage event tickets digitally',
    'onboard.getStarted': 'Get Started',
    'onboard.skip': 'Skip Tour',
  },
  ar: {
    // Common
    'common.loading': 'جارٍ التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.amount': 'المبلغ',
    'common.date': 'التاريخ',
    'common.status': 'الحالة',
    'common.description': 'الوصف',
    'common.balance': 'الرصيد',
    'common.currency': 'ل.س',

    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'إنشاء حساب',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.phoneNumber': 'رقم الهاتف',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.dontHaveAccount': 'ليس لديك حساب؟',
    'auth.alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'auth.signUp': 'إنشاء حساب',
    'auth.signIn': 'تسجيل الدخول',
    'auth.role': 'أنا',
    'auth.passenger': 'راكب',
    'auth.driver': 'سائق',
    'auth.merchant': 'تاجر',
    'auth.eventAdmin': 'منظم فعاليات',
    'auth.accountType': 'نوع الحساب',
    'auth.getStartedDescription': 'ابدأ مع محفظتك الرقمية في دقائق',
    'auth.fullNamePlaceholder': 'اسمك الكامل',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.phoneNumberPlaceholder': 'XXX XXX XXX',
    'auth.createPasswordPlaceholder': 'أنشئ كلمة مرور قوية',
    'auth.confirmPasswordPlaceholder': 'أكد كلمة المرور',
    'auth.signInHere': 'سجل دخولك هنا',
    'auth.signUpHere': 'أنشئ حساباً مجانياً',
    'auth.accessDescription': 'ادخل إلى محفظتك الرقمية وأدر مدفوعاتك',
    'auth.enterPasswordPlaceholder': 'أدخل كلمة المرور',
    'auth.rememberMe': 'تذكرني',

    'common.optional': 'اختياري',

    // Role Features
    'features.digitalWallet': 'الوصول للمحفظة الرقمية',
    'features.qrPayments': 'مدفوعات رمز QR',
    'features.eventTickets': 'شراء تذاكر الفعاليات',
    'features.transactionHistory': 'تاريخ المعاملات',
    'features.driverDashboard': 'لوحة تحكم السائق',
    'features.earningsTracking': 'تتبع الأرباح',
    'features.qrGeneration': 'إنشاء رمز QR',
    'features.tripManagement': 'إدارة الرحلات',
    'features.businessDashboard': 'لوحة تحكم العمل',
    'features.paymentProcessing': 'معالجة المدفوعات',
    'features.analyticsInsights': 'التحليلات والرؤى',
    'features.customerManagement': 'إدارة العملاء',
    'features.eventCreation': 'إنشاء الفعاليات',
    'features.ticketManagement': 'إدارة التذاكر',
    'features.attendeeAnalytics': 'تحليلات الحضور',
    'features.revenueTracking': 'تتبع الإيرادات',

    // Registration Features Headers
    'registration.personalAccountFeatures': 'ميزات الحساب الشخصي',
    'registration.driverAccountFeatures': 'ميزات حساب السائق',
    'registration.businessAccountFeatures': 'ميزات حساب العمل',
    'registration.eventOrganizerFeatures': 'ميزات منظم الفعاليات',
    'registration.whyChooseTickets': 'لماذا تختار تذاكر؟',
    'registration.bankGradeSecurity': 'أمان وتشفير بمستوى البنوك',
    'registration.instantTransactions': 'معاملات فورية وتحديثات في الوقت الفعلي',
    'registration.customerSupport': 'دعم عملاء 24/7',
    'registration.lowFees': 'رسوم منخفضة وتسعير شفاف',
    'registration.soc2Certified': 'معتمد SOC 2',
    'registration.iso27001': 'ISO 27001',
    'registration.pciCompliant': 'متوافق مع PCI',
    'registration.joinRevolution': 'انضم إلى ثورة الدفع الرقمي',
    'registration.backToHome': 'عودة إلى الرئيسية',

    // Login Page
    'login.welcomeBack': 'مرحباً بعودتك',
    'login.secure': 'آمن',
    'login.encrypted': 'مشفر',
    'login.private': 'خاص',

    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.wallet': 'المحفظة',
    'nav.transactions': 'المعاملات',
    'nav.scanner': 'ماسح QR',
    'nav.events': 'الفعاليات',
    'nav.tickets': 'تذاكري',
    'nav.earnings': 'الأرباح',
    'nav.trips': 'الرحلات',
    'nav.verification': 'التوثيق',
    'nav.qrcode': 'رمز QR',
    'nav.business': 'العمل',
    'nav.management': 'الإدارة',
    'nav.analytics': 'التحليلات',
    'nav.users': 'المستخدمون',
    'nav.disputes': 'النزاعات',
    'nav.verificationReview': 'توثيق السائقين',
    'nav.support': 'الدعم',
    'nav.settings': 'الإعدادات',
    'nav.profile': 'الملف الشخصي',

    // Wallet
    'wallet.title': 'المحفظة الرقمية',
    'wallet.balance': 'الرصيد الحالي',
    'wallet.recharge': 'شحن المحفظة',
    'wallet.rechargeAmount': 'مبلغ الشحن',
    'wallet.paymentMethod': 'طريقة الدفع',
    'wallet.mtnCash': 'إم تي إن كاش',
    'wallet.syriatelCash': 'سيرياتيل كاش',
    'wallet.shamCash': 'شام كاش',
    'wallet.fatora': 'فاتورة',
    'wallet.stripe': 'بطاقة ائتمانية',
    'wallet.rechargeSuccess': 'تم شحن المحفظة بنجاح',
    'wallet.insufficientBalance': 'رصيد غير كافٍ',

    // Transactions
    'transactions.title': 'سجل المعاملات',
    'transactions.recent': 'المعاملات الأخيرة',
    'transactions.payment': 'دفع',
    'transactions.recharge': 'شحن',
    'transactions.refund': 'استرداد',
    'transactions.withdrawal': 'سحب',
    'transactions.pending': 'معلق',
    'transactions.completed': 'مكتمل',
    'transactions.failed': 'فاشل',
    'transactions.cancelled': 'ملغى',
    'transactions.to': 'إلى',
    'transactions.from': 'من',

    // QR Scanner
    'scanner.title': 'ماسح رمز QR',
    'scanner.scanToPayDriver': 'امسح رمز السائق للدفع',
    'scanner.scanToPayMerchant': 'امسح رمز التاجر للدفع',
    'scanner.scanning': 'جارٍ المسح...',
    'scanner.paymentSuccess': 'تم الدفع بنجاح',
    'scanner.paymentFailed': 'فشل الدفع',
    'scanner.quantity': 'عدد التذاكر',

    // Events
    'events.title': 'الفعاليات',
    'events.upcoming': 'الفعاليات القادمة',
    'events.myEvents': 'فعالياتي',
    'events.createEvent': 'إنشاء فعالية',
    'events.eventTitle': 'عنوان الفعالية',
    'events.eventDescription': 'وصف الفعالية',
    'events.eventLocation': 'المكان',
    'events.eventDate': 'التاريخ',
    'events.eventPrice': 'سعر التذكرة',
    'events.availableTickets': 'التذاكر المتاحة',
    'events.buyTicket': 'شراء تذكرة',
    'events.ticketPurchased': 'تم شراء التذكرة بنجاح',

    // Driver
    'driver.title': 'لوحة تحكم السائق',
    'driver.earnings': 'الأرباح',
    'driver.todayEarnings': 'أرباح اليوم',
    'driver.weekEarnings': 'أرباح الأسبوع',
    'driver.monthEarnings': 'أرباح الشهر',
    'driver.generateQR': 'إنشاء رمز QR',
    'driver.activeTrip': 'الرحلة النشطة',
    'driver.startTrip': 'بدء الرحلة',
    'driver.endTrip': 'إنهاء الرحلة',
    'driver.route': 'المسار',
    'driver.ticketFee': 'أجرة التذكرة',
    'driver.passengerCount': 'الركاب',
    'driver.analytics': 'تحليلات السائق',
    'driver.performance': 'الأداء',
    'driver.efficiency': 'الكفاءة',
    'driver.monthlyComparison': 'مقارنة شهرية',
    'driver.hourlyPerformance': 'الأداء بالساعة',
    'driver.locationPerformance': 'أداء المواقع',
    'driver.ratingDistribution': 'توزيع التقييمات',
    'driver.performanceMetrics': 'مقاييس الأداء',
    'driver.earningsBreakdown': 'تفصيل الأرباح',
    'driver.todaySnapshot': 'لقطة اليوم',
    'driver.exportAnalytics': 'تصدير التحليلات',
    'driver.earningsTrend': 'اتجاه الأرباح',
    'driver.dailyAverage': 'المعدل اليومي',
    'driver.weeklyAverage': 'المعدل الأسبوعي',
    'driver.monthlyAverage': 'المعدل الشهري',
    'driver.totalNetEarnings': 'إجمالي الأرباح الصافية',
    'driver.averagePerTrip': 'المعدل لكل رحلة',
    'driver.totalDistance': 'إجمالي المسافة',
    'driver.totalDuration': 'إجمالي المدة',
    'driver.earningsPerHour': 'الأرباح لكل ساعة',
    'driver.earningsPerKm': 'الأرباح لكل كيلومتر',
    'driver.cancellationRate': 'معدل الإلغاء',
    'driver.overallRating': 'التقييم العام',
    'driver.efficiencyRating': 'تقييم الكفاءة',
    'driver.excellent': 'ممتاز',

    // Driver Verification
    'driver.verification.title': 'توثيق السائق',
    'driver.verification.description': 'أكمل توثيق السائق لتبدأ الربح مع تذاكر',
    'driver.verification.status.title': 'حالة التوثيق',
    'driver.verification.status.not_submitted': 'لم يتم التقديم',
    'driver.verification.status.pending': 'قيد المراجعة',
    'driver.verification.status.approved': 'موافق عليه',
    'driver.verification.status.rejected': 'مرفوض',
    'driver.verification.progress': 'التقدم',
    'driver.verification.driverInfo': 'معلومات السائق',
    'driver.verification.driverInfoDesc': 'قدم تفاصيل السائق والمركبة',
    'driver.verification.licenseNumber': 'رقم رخصة القيادة',
    'driver.verification.licenseNumberPlaceholder': 'أدخل رقم رخصة القيادة',
    'driver.verification.licenseExpiry': 'تاريخ انتهاء الرخصة',
    'driver.verification.vehicleType': 'نوع المركبة',
    'driver.verification.selectVehicleType': 'اختر نوع المركبة',
    'driver.verification.vehicleModel': 'موديل المركبة',
    'driver.verification.vehicleModelPlaceholder': 'مثال: تويوتا هايس 2020',
    'driver.verification.vehiclePlate': 'رقم لوحة المركبة',
    'driver.verification.vehiclePlatePlaceholder': 'مثال: 123456 دمشق',
    'driver.verification.routeName': 'اسم المسار',
    'driver.verification.routeNamePlaceholder': 'مثال: دمشق-حلب',
    'driver.verification.routeDescription': 'وصف المسار',
    'driver.verification.routeDescriptionPlaceholder': 'اصف مساراتك ومحطاتك المعتادة',
    'driver.verification.documents': 'الوثائق المطلوبة',
    'driver.verification.documentsDesc': 'ارفع صور واضحة أو مسح ضوئي لوثائقك',
    'driver.verification.documentTypes.license_front': 'رخصة القيادة (الوجه الأمامي)',
    'driver.verification.documentTypes.license_back': 'رخصة القيادة (الوجه الخلفي)',
    'driver.verification.documentTypes.vehicle_registration': 'تسجيل المركبة',
    'driver.verification.documentTypes.vehicle_photo': 'صورة المركبة',
    'driver.verification.viewDocument': 'عرض الوثيقة',
    'driver.verification.submit': 'تقديم للمراجعة',
    'driver.verification.invalidFileType': 'يرجى رفع ملفات صور (JPG, PNG) أو PDF فقط',
    'driver.verification.fileTooLarge': 'يجب أن يكون حجم الملف أقل من 5 ميجابايت',
    'driver.verification.documentUploaded': 'تم رفع الوثيقة بنجاح',
    'driver.verification.uploadFailed': 'فشل في رفع الوثيقة. يرجى المحاولة مرة أخرى.',
    'driver.verification.fillRequired': 'يرجى ملء جميع الحقول المطلوبة',
    'driver.verification.uploadAllDocuments': 'يرجى رفع جميع الوثائق المطلوبة',
    'driver.verification.submitted': 'تم تقديم التوثيق بنجاح! سيتم إشعارك عند المراجعة.',
    'driver.verification.rejectedMessage': 'تم رفض توثيقك. يرجى مراجعة الملاحظات وإعادة التقديم.',
    'driver.verification.approvedMessage': 'تهانينا! تم الموافقة على توثيق السائق. يمكنك الآن البدء في قبول الركاب.',
    'driver.verification.vehicleTypes.bus': 'باص',
    'driver.verification.vehicleTypes.microbus': 'ميكروباص',
    'driver.verification.vehicleTypes.taxi': 'تاكسي',
    'driver.verification.vehicleTypes.private_car': 'سيارة خاصة',
    'driver.verification.vehicleTypes.motorcycle': 'دراجة نارية',
    'driver.verification.vehicleTypes.truck': 'شاحنة',
    'common.saving': 'جارٍ الحفظ...',

    // Merchant
    'merchant.title': 'لوحة تحكم التاجر',
    'merchant.business': 'معلومات العمل',
    'merchant.businessName': 'اسم العمل',
    'merchant.businessCategory': 'الفئة',
    'merchant.generateQR': 'إنشاء رمز دفع QR',
    'merchant.qrAmount': 'مبلغ الدفع',

    // Admin
    'admin.title': 'لوحة تحكم المدير',
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.systemAnalytics': 'تحليلات النظام',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.totalTransactions': 'إجمالي المعاملات',
    'admin.totalRevenue': 'إجمالي الإيرادات',
    'admin.disputes': 'النزاعات',

    // App Name
    'app.name': 'تذاكر',
    'app.subtitle': 'محفظة رقمية ونظام دفع',
    'app.welcome': 'مرحباً بك في تذاكر',
    'app.description': 'محفظتك الرقمية للمدفوعات السلسة وتذاكر الفعاليات والنقل في سوريا.',

    // Onboarding
    'onboard.welcome': 'مرحباً بك في تذاكر!',
    'onboard.step1.title': 'محفظة رقمية',
    'onboard.step1.desc': 'احفظ وأدر أموالك رقمياً بأمان',
    'onboard.step2.title': 'دفع بـ QR',
    'onboard.step2.desc': 'ادفع للنقل والمشتريات فوراً',
    'onboard.step3.title': 'تذاكر الفعاليات',
    'onboard.step3.desc': 'اشترِ وأدر تذاكر الفعاليات رقمياً',
    'onboard.getStarted': 'ابدأ الآن',
    'onboard.skip': 'تخطي الجولة',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language
    if (savedLang && ['en', 'ar'].includes(savedLang)) {
      setLanguage(savedLang)
    }
  }, [])

  useEffect(() => {
    localStorage.setItem('language', language)
    document.documentElement.lang = language
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
  }, [language])

  const t = (key: string, params?: Record<string, string>) => {
    let translation = translations[language][key as keyof typeof translations[typeof language]] || key
    
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{{${param}}}`, value)
      })
    }
    
    return translation
  }

  const value = {
    language,
    setLanguage,
    t,
    isRTL: language === 'ar'
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}